//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjectHospital
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BillData
    {
        public int BillNo { get; set; }

        [Required(ErrorMessage = "Doctor Fees is required")]
        public int DoctorFees { get; set; }

        public Nullable<int> RoomCharge { get; set; }
        public Nullable<int> OperationCharge { get; set; }

        [Required(ErrorMessage = "Medicine fees is required")]
        public int MedicineFees { get; set; }

        public Nullable<int> TotalDays { get; set; }

        [Required(ErrorMessage = "Lab fees is required")]
        public int LabFees { get; set; }

        public int TotalAmount { get; set; }

        [Required(ErrorMessage = "Patient Id is required")]
        public int PatientID { get; set; }

        [Required(ErrorMessage = "Appointment Id is required")]
        public int AppointmentId { get; set; }
    
        public virtual PatientTreatment PatientTreatment { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
