//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjectHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab
    {
        public int ReportId { get; set; }
        public System.DateTime TestDate { get; set; }
        public string Remarks { get; set; }
        public string TestType { get; set; }
        public int PatientID { get; set; }
        public int AppointmentId { get; set; }
    
        public virtual PatientTreatment PatientTreatment { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
