//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjectHospital
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Lab
    {
        public int ReportId { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public System.DateTime TestDate { get; set; }

        public string Remarks { get; set; }

        [Required(ErrorMessage = "Test type is Required !")]
        public string TestType { get; set; }

        [Required(ErrorMessage = "Patient id is Required !")]
        public int PatientID { get; set; }

        [Required(ErrorMessage = "Appointment is Required !")]
        public int AppointmentId { get; set; }
    
        public virtual PatientTreatment PatientTreatment { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
